rvm:
  - 1.8.7
  - 1.9.3

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  - RADIANT_VERSION=1.1.2 DB=mysql
  - RADIANT_VERSION=1.1.2 DB=postgres
  - RADIANT_VERSION=master DB=mysql
  - RADIANT_VERSION=master DB=postgres

notifications:
  recipients:
    - jim+travis@saturnflyer.com
  irc: "irc.freenode.org#radiantcms"
